backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  publish_mode: editorial_workflow
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "tarot-card" # Used in routes, e.g., /admin/collections/blog
    label: "Tarot Card" # Used in the UI
    folder: "_posts/tarot-card" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Number", name: "number", widget: "number"}
      - {label: "Featured Image", name: "thumbnail", widget: "image" , required: false}
      - {label: "Description", name: "description", widget: "list"}
      - {label: "Meaning", name: "meaning", widget: "markdown"}
      - {label: "Suit", name: "suit", widget: "select", options: ["Cups", "Pentacles", "Swords", "Wands", "Does Not Apply"] , required: false}
      - {label: "Element", name: "element", widget: "select", options: ["Air", "Fire", "Earth", "Water", "Does Not Apply"] , required: false}
      - {label: "Reversed Meaning", name: "reversedMeaning", widget: "markdown" , required: false}
      - {label: "Yes or No", name: "yes-or-no", widget: "select", options: ["Yes", "No", "Does Not Apply"] , required: false}
      - {label: "Arcana", name: "arcana", widget: "select", options: ["Major", "Minor", "Does Not Apply"] , required: false}
      - {label: "Keywords [tags]", name: "keywords", widget: "list" , required: false}
      - {label: "Kaballah Letter", name: "kaballah-letter", widget: "string" , required: false} 
      - {label: "Astrology", name: "kaballah-letter", widget: "select", options: ["Aquarius", "Pisces", "Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo", "Libra", "Scorpio", "Sagittarius", "Capricorn"] , required: false}
      - {label: "Numerology Link", name: "numerology-link", widget: "string"}
      - {label: "Tree of Life Pathway", name: "tree-of-life", widget: "string" , required: false}
      - {label: "Chakra", name: "chakra", widget: "select", options: ["Root Chakra", "Sacral Chakra", "Solar Plexus Chakra", "Heart Chakra", "Throat Chakra", "Third Eye Chakra", "Crown Chakra"] , required: false}

